# Generated by Django 4.2.7 on 2023-12-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alter_vibracion_valor_numerico'),
    ]

    operations = [
    ]
