# Generated by Django 4.2.7 on 2023-12-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_auto_20231203_1825'),
    ]

    operations = [
    ]
